version: 2
updates:
  - package-ecosystem: pip
    directory: /aws_bedrock_demo
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
